name: ${pluginName}
#description: Plugin description for ${pluginName}
version: ${project.parent.version}
api-version: '1.13'

main: ${project.parent.groupId}.spigot.SpigotLime

author: Sprax2013
authors: [ Sprax2013 ]
website: https://github.com/SpraxDev/LimeDevUtility