name: ${project.parent.name}
description: ${project.parent.description}
version: ${project.version}
api-version: 1.13

main: ${project.parent.groupId}.spigot.SpigotLime

author: SpraxDev
website: ${project.parent.url}