name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Caches
      - name: 'Cache: Maven-Repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./docs/version.txt') }}

      # Maven dependencies that need to be compiled manually
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
      - name: Compile Spigot 1.8.8
        uses: SpraxDev/Action-SpigotMC@v5
        with:
          versions: 1.8.8

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      # Compile the project using maven
      - name: Build with Maven
        run: 'mvn -B -Duser.name="GitHub Runner on $GITHUB_REPOSITORY (id=$GITHUB_RUN_ID)" clean package'

      # Upload the .jar files
      - name: 'Upload Build Artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: LimeDevUtility-jars
          path: |
            ./modules/lime-api/target/LimeDevUtility-Standalone.jar
            ./modules/spigot/lime-spigot/target/LimeDevUtility-Spigot.jar
            ./modules/lime-bungeecord/target/LimeDevUtility-BungeeCord.jar
